server:
  port: 8082

spring:
  application:
    name: loyalty-service
  datasource:
    url: jdbc:postgresql://localhost:5437/lmsloyaltydb
    username: lmsloyaltyuser
    password: lmsloyaltypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/