server:
  port: 8083

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # enables routing by service name

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: loyalty-service
          uri: lb://loyalty-service
          predicates:
            - Path=/loyalty/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
